config/routes.rb
Feedex::Application.routes.draw do

  resources :line_items

  resources :carts

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
  namespace :api, defaults: {format: 'json'} do
    resources :users do
      member do
        get :available_credits
      end
    end
    resources :menus
    resources :colonies
    resources :items do
      collection do
        get :available
        get :sort
      end
    end
    resources :orders do
      collection do
        post :redeem
        get :current
      end
    end
    resources :credits
    resources :sessions, only: [:create, :destroy]
    match "*path", :to => "base#route_not_found", :via => :all
  end
  
  namespace :admin do
    root "menus#index"
    get 'dashboard' => 'pages#index'

    resources :items
    resources :sold_outs
    resources :users do
      member do
        get :credits
        patch :add_credits
      end
      collection do
        get :notify
      end
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders do
      collection do
        get :revert
        get :redeem
        get :current
        get :current_redeemed
      end
    end
    resources :colonies
    resources :delivery_locations
    resources :menus

  end

  namespace :web do
    resources :menus
  end

  resources :users
  resources :menus, only: [:index]
  resources :wallet, only: [:index, :create]
  resources :orders, only: [:index, :create]
  resources :settings, only: [:index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/confirm', to: 'users#confirm', via: 'get'
  match '/signup_success', to: 'users#signup_success', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :password_resets

  resources :payments, only: [:create]



  root "menus#index"
  
end

app/models/order.rb
class Order < ActiveRecord::Base

  paginates_per 10

  ## CONSTANTS ##
  scope :today, -> {where("created_at > date(?)", Date.today)}
  serialize :items, Array

  ## VALIDATIONS ##
  validates :user, :amount, presence: true

  ## ASSOCIATIONS ##
  belongs_to :user
  has_many :order_items

  ## CALLBACKS ##
  after_create :send_order_notification
  after_create :deduct_credits

  ## INSTANCE METHODS ##
  def description
    desc = ""
    items.each do |item|
      li = item_list.select{|i| item["id"].to_i == i.id}.first
      desc += "#{li.name}, Qty : #{item['quantity']} <br/>" if li
    end
    desc
  end

  def calculate_amount
    total_amt = 0
    items.each do |i|
      item = Item.find_by_id(i["id"])
      total_amt += (item.price.to_f * i["quantity"].to_i) if item
    end
    self.amount = total_amt
  end

  def item_list
    Item.where(id: items.collect{|i| i["id"]}).all
  end

  ## CLASS METHODS ##


  ## PRIVATE METHODS ##
  private

  def deduct_credits
    user.update_attribute(:total_credits, user.available_credits)
  end

  def send_order_notification
    Notifier.order_notification(user)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all.order(created_at: :desc).page(params[:page])
  end

  def redeem
    order_id = params[:order_id]
    if order_id
      order = Order.find(order_id)
      order.redeemed = true
      order.save if order
    end
    redirect_to current_admin_orders_path
  end

  def revert
    order_id = params[:order_id]
    if order_id
      order = Order.find(order_id)
      order.redeemed = false
      order.save if order
    end
    redirect_to current_admin_orders_path
  end

  def current
      search_query = params[:search]
      if search_query
        # Search by id first
        @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => false, :id => search_query).order(id: :desc)
        # @orders = Order.today.where(:redeemed => false, :id => search_query).order(id: :desc)
        if @orders.empty?
          users_with_name = User.where{ name =~ "%#{search_query}%"}

          if users_with_name && !users_with_name.empty?
            @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => false, :user_id => users_with_name.collect(&:id)).order(id: :desc)
          end
          if @orders.empty?
            user_with_email = User.find_by_email(search_query)
            if user_with_email
              @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => false, :user_id => user_with_email.id).order(id: :desc)
            end
            if @orders.empty?
              @empty_order = "No Results Found!"

            end

          end
          
        end

      else
        @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => false).order(id: :desc) #Order.where('delivery_time BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).where(:user_id => @current_user.id, :redeemed => false)

        @sorted_orders = @orders.group_by do |order|
          order.user_id
        end

        @large_array = []

        @sorted_orders.each do |group_of_orders|
          big_hash = {}
          user_id = group_of_orders.shift
          big_hash["username"] = User.find(user_id).name
          item_sets_array = []
          group_of_orders.each do |order_group|
            order_group.each do |order|
              order.order_items.each do |order_item|
                itemset_hash = {}
                itemset_hash["main_id"] = order_item.main_id
                itemset_hash["main_title"] = Item.with_deleted.find(order_item.main_id).name
                itemset_hash["side_id"] = order_item.side_id
                    itemset_hash["side_title"] = Item.with_deleted.find(order_item.side_id).name
                    itemset_hash["quantity"] = 1

                  add_to_array = true

                  item_sets_array.each do |check_set|
                      if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                          add_to_array = false
                          check_set["quantity"] += 1
                          break
                      end
                    end # end of item_sets_array.each do 
                    item_sets_array << itemset_hash if add_to_array
              end # end of order.order_items.each do
            end # end of order_group.each do
          end # end of group_of_orders.each do
          item_sets_array.each do |hash_arr|
            hash_arr.delete("main_id")
            hash_arr.delete("side_id")
          end
          big_hash["item_sets"] = item_sets_array
          @large_array << big_hash
        end # end of sorted_orders.each do

      end
  end

  def current_redeemed
    search_query = params[:search]
      if search_query
        # Search by id first
        @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => true, :id => search_query).order(id: :desc)
        if @orders.empty?
          users_with_name = User.where{ name =~ "%#{search_query}%"}

          if users_with_name && !users_with_name.empty?
            @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => true, :user_id => users_with_name.collect(&:id)).order(id: :desc)
          end
          if @orders.empty?
            user_with_email = User.find_by_email(search_query)
            if user_with_email
              @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => true, :user_id => user_with_email.id).order(id: :desc)
            end
            if @orders.empty?
              @empty_order = "No Results Found!"

            end

          end
          
        end

      else
        @orders = Order.where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)).where(:redeemed => true).order(id: :desc) #Order.where('delivery_time BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).where(:user_id => @current_user.id, :redeemed => false)
      
        @sorted_orders = @orders.group_by do |order|
          order.user_id
        end

        @large_array = []

        @sorted_orders.each do |group_of_orders|
          big_hash = {}
          user_id = group_of_orders.shift
          big_hash["username"] = User.find(user_id).name
          item_sets_array = []
          group_of_orders.each do |order_group|
            order_group.each do |order|
              order.order_items.each do |order_item|
                itemset_hash = {}
                itemset_hash["main_id"] = order_item.main_id
                itemset_hash["main_title"] = Item.with_deleted.find(order_item.main_id).name
                itemset_hash["side_id"] = order_item.side_id
                    itemset_hash["side_title"] = Item.with_deleted.find(order_item.side_id).name
                    itemset_hash["quantity"] = 1

                  add_to_array = true

                  item_sets_array.each do |check_set|
                      if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                          add_to_array = false
                          check_set["quantity"] += 1
                          break
                      end
                    end # end of item_sets_array.each do 
                    item_sets_array << itemset_hash if add_to_array
              end # end of order.order_items.each do
            end # end of order_group.each do
          end # end of group_of_orders.each do
          item_sets_array.each do |hash_arr|
            hash_arr.delete("main_id")
            hash_arr.delete("side_id")
          end
          big_hash["item_sets"] = item_sets_array
          @large_array << big_hash
        end # end of sorted_orders.each do


      end

      respond_to do |format|
        format.html
        format.csv do
          response.headers['Content-Type'] ||= 'text/csv'
          response.headers['Content-Disposition'] = "attachment; filename=dailyreport.csv"
          send_data csviy(@orders), :filename => "DailyReport.csv"
        end
      end
    
  end

  def csviy(orders)
    CSV.generate do |csv|
      column_headers = ["Order ID", "Customer Name", "Main", "Side", "Qty", "Amount", "Trx Time", "Redemption Time"]
      csv << column_headers
      orders.each do |order|
        
        item_sets_array = []
        order.order_items.each do |order_item|
          itemset_hash = {}
          itemset_hash["main_id"] = order_item.main_id
          itemset_hash["main_title"] = Item.with_deleted.find(order_item.main_id).name
          itemset_hash["side_id"] = order_item.side_id
          itemset_hash["side_title"] = Item.with_deleted.find(order_item.side_id).name
          itemset_hash["quantity"] = 1
          add_to_array = true
          item_sets_array.each do |check_set|
              if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                  add_to_array = false
                  check_set["quantity"] += 1
                  break
              end
          end # end of item_sets_array.each do
          item_sets_array << itemset_hash if add_to_array
        end

        first_time = true
        item_sets_array.each do |set| 
          loaded_array = []
          if first_time
            loaded_array << order.id
            loaded_array << order.user.name
          else
            loaded_array << " "
            loaded_array << " "
          end
          loaded_array << set["main_title"]
          loaded_array << set["side_title"]
          loaded_array << set["quantity"]
          if first_time
            loaded_array << ActionController::Base.helpers.number_to_currency(order.amount)
            loaded_array << order.created_at 
            loaded_array << order.updated_at
          else

          end
          csv << loaded_array
          first_time = false
        end

        # csv << loaded_array
      end

    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	layout false
	include CurrentCart
	before_action :set_cart, only: [:index, :create]
	def index
		
	end

	def create
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
		order = Order.new(:user_id => @current_user.id, :delivery_time => order_params[:delivery_time])

		total_amt = 0
		item_sets = order_params[:item_sets]

		main_count = []

		item_sets.each do |i|
			main_item = Item.find_by_id(i["main_id"])
			side_item = Item.find_by_id(i["side_id"])
			total_amt += main_item.price.to_f if main_item
			total_amt += side_item.price.to_f if side_item
          	main_count_hash = {}
          	main_count_hash[:item_id] = main_item.id
          	main_count_hash[:item] = main_item
          	main_count_hash[:count] = 1
          	main_add_to_array = true
          	main_count.each do |check_count|
          		if check_count[:item_id] == main_count_hash[:item_id]
          			add_to_array = false
          			check_count[:count] += 1
          			break
          		end
          	end
          	main_count << main_count_hash if main_add_to_array

          	side_count_hash = {}
          	side_count_hash[:item_id] = side_item.id
          	side_count_hash[:item] = side_item
          	side_count_hash[:count] = 1
          	side_add_to_array = true
          	main_count.each do |check_count|
          		if check_count[:item_id] == side_count_hash[:item_id]
          			add_to_array = false
          			check_count[:count] += 1
          			break
          		end
          	end
          	main_count << side_count_hash if side_add_to_array
		end

		main_count.each do |item_hash|
			item = item_hash[:item]
			if item.items_menus.last.quantity < item_hash[:count]
				redirect_to menus_url, :flash => { :error => "#{item.name} sold out!" } and return
			end
		end

		order.amount = total_amt

		if @current_user.total_credits >= total_amt
			if order.save
				order_params[:item_sets].each do |item|
					orderitem = OrderItem.new(:order_id => order.id, :main_id => item["main_id"].to_i, :side_id => item["side_id"].to_i) if item
              		orderitem.save!
				end

				# Reduce quantity
				item_sets.each do |i|
					main_item = Item.find_by_id(i["main_id"])
					side_item = Item.find_by_id(i["side_id"])
					main_item.items_menus.last.decrement!(:quantity)
					side_item.items_menus.last.decrement!(:quantity)
				end

				# Send email confirmation
				OrderMailer.send_order_confirmation_email(order).deliver

				# Delete current cart items
				@cart.line_items.each do |l|
					l.delete
				end
				
				redirect_to orders_url and return
			else
				# Invalid order
				# Refer to Saleswhale for error handling
				puts "Invalid Order"
			end
		else
			# Insufficent balance
			# Refer to Saleswhale for error handling
			puts "Insufficent Balance "
			redirect_to menus_url and return
		end

	end

	private

	def order_params
		if params[:order].present?
        	params[:order].merge!({user_id: @current_user.id})
        	return params[:order].permit(:user_id, :delivery_time, :item_sets => [:main_id, :side_id] )
      	end
	end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

  def location_set
    ["All Locations"] + DeliveryLocation.all.collect{|l| [l.name, l.id]}
  end

end

app/helpers/api/orders_helper.rb
module Api::OrdersHelper
end

app/views/admin/orders/current.html.erb
<div id="allitems">
	<h1>Today's Orders</h1>
	<h3>Showing <b>Unredeemed</b> Orders only    <%= link_to "See Redeemed Orders", current_redeemed_admin_orders_path %></h3>
	<br>
	<%= form_tag current_admin_orders_path, :method => 'get' do %>
		<%= text_field_tag :search, params[:search], placeholder: "Enter Order ID Here" %>
		<%= submit_tag "Search", :name => nil, value: "Search",style: "background-color:#282828;color:#FFF;text-indent:0px !important; font-size:1.0em;" %>
	<% end %>

	<%= link_to "Clear Search", current_admin_orders_path %>

	<hr />

	<table width="100%">
		<tr>
			<th>Order ID</th>
			<th>Username</th>
			<th>Main</th>
			<th>Side</th>
			<th>Qty.</th>
			<th>Redeemed?</th>
			<th>Click to Redeem</th>
		</tr>
		<% @orders.each do |order| %>
			<tr class="<%= cycle('oddrow', 'evenrow') %>">
			<td><%= order.id %></td>
			<td><%= order.user.name %></td>
			<% item_sets_array = [] %>
			<% order.order_items.each do |order_item| %>
				<% itemset_hash = {}
					itemset_hash["main_id"] = order_item.main_id
				   itemset_hash["main_title"] = Item.with_deleted.find(order_item.main_id).name
				   itemset_hash["side_id"] = order_item.side_id
				   itemset_hash["side_title"] = Item.with_deleted.find(order_item.side_id).name
				   itemset_hash["quantity"] = 1
				   add_to_array = true
				   item_sets_array.each do |check_set|
                		if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                  			add_to_array = false
                  			check_set["quantity"] += 1
                  			break
                		end
              		end # end of item_sets_array.each do 
              		item_sets_array << itemset_hash if add_to_array
				%>
			<% end %>
			<% count = item_sets_array.count %>
			<td>
			<% main_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[main_index]["main_title"] %>
				<br><hr/>
				<% main_index += 1 %>
			<% end %>
			</td>

			<td>
			<% side_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[side_index]["side_title"] %>
				<br><hr/>
				<% side_index += 1 %>
			<% end %>
			</td>

			<td>
			<% qty_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[qty_index]["quantity"] %>
				<br><hr/>
				<% qty_index += 1 %>
			<% end %>
			</td>
			<td>NO</td>
			<td><%= link_to "Redeem!", redeem_admin_orders_path(:order_id => order.id) %></td>

			</tr>

		<% end %>
	</table>
	<% if @empty_order %>
		<br>
		<%= @empty_order %>
	<% end %>

</div>

app/views/admin/orders/current_redeemed.html.erb
<div id="allitems">
	<h1>Today's Orders</h1>
	<h3>Showing <b>Redeemed</b> Orders only   <%= link_to "See Unredeemed Orders", current_admin_orders_path %></h3></h3>
	<h3><%= link_to "Export CSV", current_redeemed_admin_orders_path(format: "csv") %></h3>
	<br>
	<%= form_tag current_redeemed_admin_orders_path, :method => 'get' do %>
		<%= text_field_tag :search, params[:search], placeholder: "Enter Order ID Here" %>
		<%= submit_tag "Search", :name => nil, value: "Search",style: "background-color:#282828;color:#FFF;text-indent:0px !important; font-size:1.0em;" %>
	<% end %>

	<%= link_to "Clear Search", current_redeemed_admin_orders_path %>

	<hr />
	

		<table width="100%">
		<tr>
			<th>Order ID</th>
			<th>Username</th>
			<th>Main</th>
			<th>Side</th>
			<th>Qty.</th>
			<th>Redeemed?</th>
			<th>Click to Revert</th>
		</tr>
		<% @orders.each do |order| %>
			<tr class="<%= cycle('oddrow', 'evenrow') %>">
			<td><%= order.id %></td>
			<td><%= order.user.name %></td>
			<% item_sets_array = [] %>
			<% order.order_items.each do |order_item| %>
				<% itemset_hash = {}
					itemset_hash["main_id"] = order_item.main_id
				   itemset_hash["main_title"] = Item.with_deleted.find(order_item.main_id).name
				   itemset_hash["side_id"] = order_item.side_id
				   itemset_hash["side_title"] = Item.with_deleted.find(order_item.side_id).name
				   itemset_hash["quantity"] = 1
				   add_to_array = true
				   item_sets_array.each do |check_set|
                		if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                  			add_to_array = false
                  			check_set["quantity"] += 1
                  			break
                		end
              		end # end of item_sets_array.each do 
              		item_sets_array << itemset_hash if add_to_array
				%>
			<% end %>
			<% count = item_sets_array.count %>
			<td>
			<% main_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[main_index]["main_title"] %>
				<br><hr/>
				<% main_index += 1 %>
			<% end %>
			</td>

			<td>
			<% side_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[side_index]["side_title"] %>
				<br><hr/>
				<% side_index += 1 %>
			<% end %>
			</td>

			<td>
			<% qty_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[qty_index]["quantity"] %>
				<br><hr/>
				<% qty_index += 1 %>
			<% end %>
			</td>
			<td>YES</td>
			<td><%= link_to "Revert!", revert_admin_orders_path(:order_id => order.id) %></td>

			</tr>
		<% end %>
	</table>
	<% if @empty_order %>
		<br>
		<%= @empty_order %>
	<% end %>

</div>

app/views/admin/orders/index.html.erb
<div id="allitems">
	<h1>Order History</h1><hr />
	<table width="100%">
		<tr>
			<th>Order No.</th>
			<th>Username</th>
			<th>Main</th>
			<th>Side</th>
			<th>Qty.</th>
			<th>Amount</th>
			<th>Date</th>
			<th>Redeemed?</th>
			
		</tr>

		<%= paginate @orders %>

		<% @orders.each do |order| %>
			<tr class="<%= cycle('oddrow', 'evenrow') %>">
			<td><%= order.id %></td>
			<td><%= order.user.name %></td>
			<% item_sets_array = [] %>
			<% order.order_items.each do |order_item| %>
				<% itemset_hash = {}
					itemset_hash["main_id"] = order_item.main_id

					main_item = Item.with_deleted.find_by_id(order_item.main_id)
					side_item = Item.with_deleted.find_by_id(order_item.side_id)

					if main_item.nil?
						itemset_hash["main_title"] = "Not available"
					else
						itemset_hash["main_title"] = Item.with_deleted.find_by_id(order_item.main_id).name
					end

					if side_item.nil?
						itemset_hash["side_title"] = "Not available"
					else
						itemset_hash["side_title"] = Item.with_deleted.find_by_id(order_item.side_id).name
					end
				   itemset_hash["side_id"] = order_item.side_id
				   itemset_hash["quantity"] = 1
				   add_to_array = true
				   item_sets_array.each do |check_set|
                		if check_set["main_id"] == itemset_hash["main_id"] && check_set["side_id"] == itemset_hash["side_id"]
                  			add_to_array = false
                  			check_set["quantity"] += 1
                  			break
                		end
              		end # end of item_sets_array.each do 
              		item_sets_array << itemset_hash if add_to_array
				%>
			<% end %>
			<% count = item_sets_array.count %>
			<td>
			<% main_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[main_index]["main_title"] %>
				<br><hr/>
				<% main_index += 1 %>
			<% end %>
			</td>

			<td>
			<% side_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[side_index]["side_title"] %>
				<br><hr/>
				<% side_index += 1 %>
			<% end %>
			</td>

			<td>
			<% qty_index = 0 %>
			<% count.times do %>
				<%= item_sets_array[qty_index]["quantity"] %>
				<br><hr/>
				<% qty_index += 1 %>
			<% end %>
			</td>
			<td><%= number_to_currency(order.amount) %></td>
			<td><%= order.created_at %></td>
			<td><%= order.redeemed %></td>
		<% end %>
		
	</table>
	<%= paginate @orders %>
</div>

app/views/admin/orders/interim.html.erb
<% @large_array.each do |order| %>
			<tr class="<%= cycle('oddrow', 'evenrow') %>">
			<td><%= order["username"] %></td>
			<td><% order["item_sets"].each do |item_set| %>
					<%= item_set["main_title"] %> +
					<%= item_set["side_title"] %> X
					<%= item_set["quantity"] %> set(s)
					<br>
				<% end %>
			</td>
			<td>NO</td>


			</tr>
		<% end %>