config/routes.rb
Feedex::Application.routes.draw do

  resources :line_items

  resources :carts

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
  namespace :api, defaults: {format: 'json'} do
    resources :users do
      member do
        get :available_credits
      end
    end
    resources :menus
    resources :colonies
    resources :items do
      collection do
        get :available
        get :sort
      end
    end
    resources :orders do
      collection do
        post :redeem
        get :current
      end
    end
    resources :credits
    resources :sessions, only: [:create, :destroy]
    match "*path", :to => "base#route_not_found", :via => :all
  end
  
  namespace :admin do
    root "menus#index"
    get 'dashboard' => 'pages#index'

    resources :items
    resources :sold_outs
    resources :users do
      member do
        get :credits
        patch :add_credits
      end
      collection do
        get :notify
      end
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders do
      collection do
        get :revert
        get :redeem
        get :current
        get :current_redeemed
      end
    end
    resources :colonies
    resources :delivery_locations
    resources :menus

  end

  namespace :web do
    resources :menus
  end

  resources :users
  resources :menus, only: [:index]
  resources :wallet, only: [:index, :create]
  resources :orders, only: [:index, :create]
  resources :settings, only: [:index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/confirm', to: 'users#confirm', via: 'get'
  match '/signup_success', to: 'users#signup_success', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :password_resets

  resources :payments, only: [:create]



  root "menus#index"
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout false
  include SessionsHelper
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
    @total_price = 0.0
    @cart.line_items.each do |item|
    @total_price += Item.find(item.main_id).price
    @total_price += Item.find(item.side_id).price
    end

    @item_sets = []
    @cart.line_items.each do |i|
      item_hash = {}
      item_hash[:main_id] = i.main_id
      item_hash[:side_id] = i.side_id
      @item_sets << item_hash
    end

  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      if browser.tablet?
        format.html { redirect_to carts_url }
      elsif browser.mobile?
        format.html { redirect_to carts_url }
      else
        format.html { redirect_to menus_url }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    end

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>




<p id="notice"><%= notice %></p>

<ul>
	<% @cart.line_items.each do |item| %>
		<li><%= item.main_id %> | <%= item.side_id %></li><br>
	<% end %>
</ul>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Feedex</title>
		<meta name="description" content="Responsive Animated Border Menus with CSS Transitions" />
		<meta name="keywords" content="navigation, menu, responsive, border, overlay, css transition" />
		<meta name="author" content="Codrops" />
		<%= favicon_link_tag 'favicon.ico' %>
		<%= csrf_meta_tag %>

		<%= stylesheet_link_tag "two/normalize.css" %>
		<%= stylesheet_link_tag "two/demo.css" %>
		<%= stylesheet_link_tag "two/icons.css" %>
		<%= stylesheet_link_tag "two/idangerous.swiper.css" %>
		<%= stylesheet_link_tag "two/style5.css" %>
		<%= stylesheet_link_tag "two/stylemain.css" %>

		<%= javascript_include_tag "jquery", "jquery_ujs" %>
		<%= javascript_include_tag "two/modernizr.custom.js" %>
		<%= javascript_include_tag "two/idangerous.swiper-2.1.min.js" %>

		<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52892596-2', 'auto');
  ga('send', 'pageview');

</script>


	</head>
	<body>
		<div id="container" class="summarycontainer">




				<div id="maincontent">
				<div id="header"><h1>SUMMARY</h1><div id="cartbutton"><a href="#"><span><%= @cart.line_items.count %>&nbsp;&nbsp;</span>
				<%= image_tag("icon_cart.png") %>


				</a></div></div>

				

		
				<div id="summarybg"></div>
			<div id="summarycontent">

			<ul class="summarylist">
				<% @cart.line_items.each_with_index do |item, index| %>
					<li><%= index + 1 %><ul class="orderitems">
						<li><%= Item.find(item.main_id).name %></li>
						<li><%= Item.find(item.side_id).name %></li>
					</ul>
					<p class="summaryprice">$<%= number_with_precision(Item.find(item.main_id).price + Item.find(item.side_id).price, precision: 2) %></p>
					<%= link_to item, method: :delete, data: { confirm: 'Are you sure you want to remove this from the cart?' } do %>
						<%= image_tag("icon_dlt.png", class: "summarydlt") %>
					<% end %>
					</li><hr />
				<% end %>





				

        

			</ul>


		</div><!--end of summary content-->



					<div id="footer" class="summaryfooter">


		
			<!--<div id="addtocartbg" class="summaryatcbg"></div>-->
			<div id="addtocartbg"></div>				

			<!--<div id="addtocart" class="summaryatc">-->
			<div id="addtocart">


				<% if @current_user.total_credits >= @total_price %>

				<%= button_to 'Checkout', {:controller => "orders", :action => "create", :order => { delivery_time: DateTime.now, item_sets: @item_sets }}, class: "checkoutbtn2" %>
					
						<!--<h1>CHECKOUT</h1>-->

				<% else %>

					<%= link_to 'Top Up', {:controller => "wallet", :topup => @total_price - @current_user.total_credits}, class: "topupbtn2" %>

					<!--<h1 style="color: #FF7109;">Top Up</h1>-->
				<% end %>

			</div><!--add to cart end-->	

			
			<div id="addprice" class="checkoutprice">
					
					<h1>$<%= number_with_precision(@total_price, precision: 2) %></h1>

			</div>


		</div><!--end of footer-->




		


	</div><!--end of maincontent-->












			
			<nav id="bt-menu" class="bt-menu">
				<a href="#" class="bt-menu-trigger"><span>Menu</span></a>

				<ul>
					<li>
					<a href="/menus">
					<%= image_tag("fdxlogo.png", id: "fdxlogo") %></a>
					</li><br><br>
					<li id="btfirstli"><a href="/menus">
					<%= image_tag("icon_menu.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;TODAY'S MENU</span></a></li>
					<li><a href="/wallet">
					<%= image_tag("icon_money.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	MY WALLET</span></a></li>
					<li><a href="settings.html">
					<%= image_tag("icon_settings.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	SETTINGS</span></a></li>
					<li><%= link_to signout_path, method: "delete" do %>
					<%= image_tag("icon_logout.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	LOGOUT</span><% end %></li>
				
				</ul>

			</nav>

			<div id="navshowbg">
			</div>	
			<div id="navshow">

				<ul id="#navshowul">
					<li>
					<a href="/menus">
					<%= image_tag("fdxlogo.png", id: "fdxlogo2") %></a>


					</li><br><br><br><br><br>
					<li><a href="/menus">
					<%= image_tag("icon_menu.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;TODAY'S MENU</span></a></li>
					<li><a href="/wallet">
					<%= image_tag("icon_money.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	MY WALLET</span></a></li>
					<li><a href="settings.html">
					<%= image_tag("icon_settings.png", class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	SETTINGS</span></a></li>
					<li><%= link_to signout_path, method: "delete" do %>
					<%= image_tag('icon_logout.png', class: "menuimg") %>
					<span>&nbsp;&nbsp;&nbsp;	LOGOUT</span>
					<% end %></li>
				
				</ul>



			</div>	

		</div><!-- /container -->
	</body>

	<%= javascript_include_tag "two/classie.js" %>
	<%= javascript_include_tag "two/borderMenu.js" %>



	<script>



  function mediaqueryresponse(mql){
		 if (mql.matches){ // if 900px and bigger
		  
			$('.bt-menu-trigger').hide();
			
		 }
		 else{
		  	
		$('.bt-menu-trigger').show();


		 }
		}

		var mql = window.matchMedia("(min-width: 700px)")
		mediaqueryresponse(mql) // call listener function explicitly at run time
		mql.addListener(mediaqueryresponse) // attach listener function to listen in on state changes
			
  </script>
</html>