config/routes.rb
Feedex::Application.routes.draw do

  resources :line_items

  resources :carts

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
  namespace :api, defaults: {format: 'json'} do
    resources :users do
      member do
        get :available_credits
      end
    end
    resources :menus
    resources :colonies
    resources :items do
      collection do
        get :available
        get :sort
      end
    end
    resources :orders do
      collection do
        post :redeem
        get :current
      end
    end
    resources :credits
    resources :sessions, only: [:create, :destroy]
    match "*path", :to => "base#route_not_found", :via => :all
  end
  
  namespace :admin do
    root "menus#index"
    get 'dashboard' => 'pages#index'

    resources :items
    resources :sold_outs
    resources :users do
      member do
        get :credits
        patch :add_credits
      end
      collection do
        get :notify
      end
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders do
      collection do
        get :revert
        get :redeem
        get :current
        get :current_redeemed
      end
    end
    resources :colonies
    resources :delivery_locations
    resources :menus

  end

  namespace :web do
    resources :menus
  end

  resources :users
  resources :menus, only: [:index]
  resources :wallet, only: [:index, :create]
  resources :orders, only: [:index, :create]
  resources :settings, only: [:index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  match '/confirm', to: 'users#confirm', via: 'get'
  match '/signup_success', to: 'users#signup_success', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :password_resets

  resources :payments, only: [:create]



  root "menus#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  paginates_per 10

  before_create :create_remember_token
  before_create :generate_confirmation_token
  before_save { self.email = email.downcase }

  include ActiveModel::SecurePassword
  has_secure_password

  belongs_to :colony

  ## CONSTANTS ##

  ## VALIDATIONS ##
  #validates :name, :email, :password_digest, presence: true
  #validates :email, uniqueness: { allow_blank: true }
  #validates :email, format: { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, allow_blank: true }
  #validates :mobile, format: { with: /\A[8-9]\d{7}\z/, allow_blank: true }
  validates :name, :presence => true
  validates_presence_of :password, :on => :create
  validates :password, :confirmation => true, :on => :create
  validates :password, :length => {:minimum => 6 }, :on => :create
  validates :password, :length => {:minimum => 6 }, :confirmation => true, :allow_blank => true, :on => :update

  validates :email, uniqueness: { allow_blank: false }, :presence => true
  validates :email, :email => true
  validates :mobile, format: { with: /\A[8-9]\d{7}\z/, allow_blank: false },:presence => true, :on => :create
  validates :mobile, format: { with: /\A[8-9]\d{7}\z/, allow_blank: true }, :on => :update

  ## ASSOCIATIONS ##
  has_many :credits, dependent: :destroy
  has_many :orders, dependent: :destroy
  accepts_nested_attributes_for :credits

  ## CALLBACKS ##
  #after_create :send_welcome_notification

  def send_beta_mailer
    # Create reset token
    self.reset_password_token = loop do
      token = SecureRandom.urlsafe_base64(nil, false)
      break token unless User.exists?(reset_password_token: token)
    end
    self.reset_password_sent_at = Time.zone.now
    save!

    # Send email confirmation
    OrderMailer.send_beta_welcome_email(self).deliver
  end

  ## INSTANCE METHODS ##
  def available_credits
    credits.collect(&:amount).sum - orders.collect(&:amount).sum
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def send_password_reset
    self.reset_password_token = loop do
      token = SecureRandom.urlsafe_base64(nil, false)
      break token unless User.exists?(reset_password_token: token)
    end
    self.reset_password_sent_at = Time.zone.now
    save!
    OrderMailer.send_password_reset_email(self).deliver
  end

  ## CLASS METHODS ##


  ## PRIVATE METHODS ##
  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

  def send_welcome_notification
    Notifier.welcome_notification(self)
  end

  protected
  def generate_confirmation_token
    self.confirmation_token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless User.exists?(confirmation_token: random_token)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :load_user, :except => [:index, :new, :create, :sort]
  before_filter :require_super


  def index
    search_query = params[:search]
    if search_query
      @users = User.where(:email => search_query).page(params[:page])
      if @users.empty?
        @users = User.where{ name =~ "%#{search_query}%"}.page(params[:page])
      end
    else
      @users = params[:sort].present? ? User.order(params[:sort].downcase).page(params[:page]) : User.all.order(created_at: :desc).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.csv do
        userz = User.all.order(created_at: :desc)
        response.headers['Content-Type'] ||= 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=users.csv"
        send_data csviy(userz), :filename => "Users.csv"
      end
    end
  end

  def csviy(users)
    CSV.generate do |csv|
      column_headers = ["User Name", "Email", "Current Credits"]
      csv << column_headers
      users.each do |user|
        loaded_array = []
        loaded_array << user.name
        loaded_array << user.email
        loaded_array << user.total_credits
        csv << loaded_array
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.confirmed_at = DateTime.now
    if @user.save
      flash[:notice] = "User has been saved successfully"
      redirect_to admin_users_path
    else
      flash[:error] = "Please fix the errors below"
      render :new
    end
  end

  def edit
    @orders = Order.where("user_id = ?", params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "User has been updated successfully"
      redirect_to admin_users_path
    else
      flash[:error] = "Please fix the errors below"
      render :edit
    end
  end

  def credits
  end

  def add_credits
    if @user.update_attributes(user_params)
      flash[:notice] = "Credits added successfully"
      redirect_to admin_users_path
    else
      flash[:error] = "Please fix the errors below"
      render :credits
    end
  end

  def destroy
    unless @user.is_admin?
      @user.destroy
      flash[:notice] = "User has been deleted successfully"
    else
      flash[:error] = "User cannot be deleted"
    end
    redirect_to admin_users_path
  end

  def notify
  end

  private

  def require_super
    unless @current_admin.role == "super"
      flash[:error] = "Sorry, you are not authorized to access this resource. Off back to Orders you go!"
      redirect_to current_admin_orders_path and return
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :mobile,
                                 :colony_id, :confirmed_at, credits_attributes: [:amount, :source])
  end

  def load_user
    @user = User.where(:id => params[:id]).first
    unless @user
      flash[:error] = "User not found"
      redirect_to admin_users_path and return
    end
  end

end

app/controllers/api/users_controller.rb
module Api
  
  class UsersController < Api::BaseController
    respond_to :json
    
    skip_filter :restrict_access, only: [:create]
    
    def create
      begin
        # @user = User.new(params[:user])
        user = User.new(user_params)
        generate_auth_key user
        if user.save
          @response = {success: true, success_message: "User has been saved successfully", user: user}
        else
          @response = {success: false, error_message: "Invalid user details", errors: user.errors}
        end
      rescue Exception => e
        @response = {success: false, error_message: "error processing request, please try again later!"}
        Rails.logger.error "Stacktrace: \n\t#{e.backtrace.join("\n\t")}"
      end
      respond_with @response.to_json, location: ""
    end
    
    def update
      begin
        auth_key = request.headers["X-Auth"]
        user = User.where(id: params[:id], auth_key: auth_key).first
        if user && params[:user].present?
          if user.update_attributes(user_params)
            @response = {success: true, success_message: "User has been updated successfully"}
          else 
            @response = {success: false, error_message: "Please fix the errors", errors: user.errors}
          end
        else
          @response = {success: false, error_message: "Either wrong combination of id and auth_token OR missing user parameters to update"}
        end
      rescue Exception => e
        @response = {success: false, error_message: "error processing request, please try again later!"}
        Rails.logger.error "Stacktrace: \n\t#{e.backtrace.join("\n\t")}"
      end
      render json: @response
    end

    def available_credits
      begin
        auth_key = request.headers["X-Auth"]
        user = User.where(id: params[:id], auth_key: auth_key).first
        if user
          @response = {success: true, available_credits: user.available_credits}
        else
          @response = {success: false, error_message: "Invalid User", errors: "Invalid user or user not found"}
        end
      rescue Exception => e
        @response = {success: false, error_message: "error processing request, please try again later!"}
        Rails.logger.error "Stacktrace: \n\t#{e.backtrace.join("\n\t")}"
      end
      render json: @response
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :mobile,
                                   :colony_id, credits_attributes: [:amount, :source])
    end  
  
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout false
  include SessionsHelper
  def index
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      # Send mailer
      OrderMailer.send_account_activation_email(@user).deliver
  		redirect_to signup_success_url
  	else
      if @user.errors
        gon.errorz = @user.errors.full_messages[0]
      else

      end
  		
  		render :new
  	end
  end

  def update
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)

    if @current_user.update_attributes(user_params)
      flash[:notice] = "Your account settings were successfully updated."
      redirect_to settings_url
    else
      flash[:error] = @current_user.errors.full_messages[0].to_s
      redirect_to settings_url
    end
  end

  def signup_success
  end

  def confirm
    confirmation_token = params[:confirmation]
    user = User.where(confirmation_token: confirmation_token).first
    if user
      user.confirmed_at = DateTime.now
      user.save!
      sign_in user
      redirect_to menus_url
    else
      flash[:error] = "Sorry, something went wrong."
      redirect_to root_url
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation,
                                 :colony_id, credits_attributes: [:amount, :source])
  end


  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div>
	<%= f.label "User Name" %>
	<%= f.text_field :name %>
	<%= inline_errors(user, :name) %>
</div><br>
<div>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= inline_errors(user, :email) %>
</div><br>
<div>
	<%= f.label :colony %>
	<%= f.select :colony_id, Colony.all.collect{|c| [c.name, c.id]} %>
	<%= inline_errors(user, :colony_id) %>
</div><br>
<div>
	<%= f.label :mobile %>
	<%= f.text_field :mobile %>
	<%= inline_errors(user, :mobile) %>
</div><br>
<% if user.new_record? %>
	<div>
		<%= f.label "Password" %>
		<%= f.password_field :password %>
		<%= inline_errors(user, :password) %>
	</div><br>
	<div>
		<%= f.label "Cfm Password" %>
		<%= f.password_field :password_confirmation %>
		<%= inline_errors(user, :password_confirmation) %>
	</div><br>
<% else %>
	<div>
		<%= f.label "Credits YTD" %>
		<%= user.total_credits %>
	</div><br><br>
	<div>
		<h3>Credits Top Up History</h3>
		<table>
			<tr>
				<th>Date</th>
				<th>Amount</th>
			</tr>
			<% user.credits.each do |cr| %>
				<tr>
					<td><%= cr.created_at.strftime("%d %b, %Y") %></td>
					<td><%= number_to_currency(cr.amount) %></td>
				</tr>
				<% end %>
		</table>
	</div><br><br>
<% end %>

app/views/admin/users/credits.html.erb
<div id="newitem">

<%= link_to "< Back", admin_users_path, :class => "backbutton" %>

<h1>Add New Credits</h1><hr />
	
	<div id="newitembox">

<%= form_for @user, url: add_credits_admin_user_path(@user) do |f| %>
	<div>
		<%= f.label "Add Credits" %>
		<%= f.fields_for :credits, @user.credits.build do |cr| %>
			<%= cr.text_field :amount %><br/>
			<%= custom_error("Please enter a valid amount") unless @user.errors.blank? %>
			<%= cr.hidden_field :source, value: Credit::Sources[:admin] %>
		<% end %>
	</div>
	<div>
		<%= f.submit "Update" , :class => "submitnewitem" %>
	</div>
<% end %>

</div><!--end of newitembox-->



</div><!--end of newitem-->	

app/views/admin/users/edit.html.erb
<div id="edititem">

	<%= link_to "< Back", admin_users_path, :class => "backbutton" %>

	<h1>Edit User Details</h1><hr />
	
	<div id="newitembox">

<%= form_for [:admin, @user], multipart: true do |f| %>
	<%= render :partial => "form", locals: { user: @user, f: f } %>
	<div>
		<%= f.submit "Update", :class => "submitedititem" %>
		<% unless @user.is_admin? %>
		 | <%= link_to 'Delete User', admin_user_path(@user), method: :delete, confirm: "Are you sure?" %>
		 <% end %>
	</div>
<% end %>

<br><br>
<h3>Order Transaction History</h3>
<table>
			<tr>
				<th>Order Date</th>
				<th>Amount Spent</th>
				<th>Order Items</th>

			</tr>
			<% @orders.each do |order| %>
				<tr>
					<td><%= order.created_at.strftime("%d %b, %Y") %></td>
					<td><%= number_to_currency(order.amount) %></td>
					<td><% order.order_items.each do |order_item| %>
							<%= Item.find(order_item.main_id).name %> + <%= Item.find(order_item.side_id).name %>
						<% end %>
					</td>

				</tr>
				<% end %>
		</table>

</div><!--end of newitembox-->


</div><!--end of edititem-->	

app/views/admin/users/index.html.erb
<div id="allitems">
	<h1>All Users</h1><hr />
	<h3><%= link_to "Export CSV", admin_users_path(format: "csv") %></h3>
	
	<%= link_to raw(image_tag('addnewbutton.png')), new_admin_user_path, class: 'addnew' %>

	<%= form_tag admin_users_path, method: :get do %>
		<%= text_field_tag :search, params[:search], placeholder: "Enter User Email / Name" %>
		<%= submit_tag "Search", :name => nil, value: "Search",style: "background-color:#282828;color:#FFF;text-indent:0px !important; font-size:1.0em;" %>
	<% end %>

	<%= form_tag admin_users_path, method: :get, id: 'sort_users' do %>
		<% if params[:sort].present? %>
			<%= select_tag "sort", options_for_select(["Name", "Email"]), selected: params[:sort], class: "sortusersdropdown" %>
		<% else %>
			<%= select_tag "sort", options_for_select(["Name", "Email"]), prompt: "Sort By", class: "sortusersdropdown" %>
		<% end %>
	<% end %>
	<%= link_to "Clear Search", admin_users_path %>

	<%= paginate @users %>
	<table width="100%">
	
		<tr>
			<th>User Name</th>
			<th>Email</th>
			<th>Colony</th>	
			<th>Credits</th>
			<th>Edit Credits</th>
		</tr>
		<% @users.each do |user| %>
			<tr class="<%= cycle('oddrow', 'evenrow') %>">
				<td><%= link_to user.name, edit_admin_user_path(user) %></td>
				<td><%= user.email %></td>
				<td><%= user.colony.name %></td>
				<td><%= user.total_credits %></td>
				<td><%= link_to raw(image_tag('editcreditbutton.png')), credits_admin_user_path(user) %></td>
			</tr>
		<% end %>
	</table>
	<br><br>
	<%= paginate @users %>
</div>

<script>
	$('select#sort').change(function(){
		$('form#sort_users').submit();
	});
</script>

app/views/admin/users/new.html.erb
<div id="newitem">


<%= link_to "< Back", admin_users_path, :class =>"backbutton" %>

<h1>Add New User</h1><hr />
	
	<div id="newitembox">


<%= form_for [:admin, @user], multipart: true do |f| %>
	<%= render :partial => "form", locals: { user: @user, f: f } %>
	<div>
		<%= f.submit "Add New", :class=>"submitnewitem" %>
	</div>
<% end %>

</div><!--end of newitembox-->


</div><!--end of newitem-->	